---
- name: Install Packages
  xbps:
    pkg: grafana
    state: present

- name: Configure Firewall
  template:
    src: grafana.rules.j2
    dest: /etc/iptables.d/grafana.rules
    owner: root
    group: root
    mode: 0640
  notify:
    - iptables
  when: grafana.public_bind | default(false)

- name: Enable Grafana
  runit:
    name: grafana
    enabled: true
    state: started

- name: Configure nginx base-site
  include_role:
    name: nginx
    tasks_from: base-site
  vars:
    - site: "{{ grafana.site }}"

- name: Install location file
  copy:
    src: grafana_root.conf
    dest: /etc/nginx/locations.d/{{ grafana.site.urls | first }}/
    owner: root
    group: root
    mode: 0644
  notify:
    - nginx
